services:
  app:
    build:
      context: .
    image: test-vue-deploy-app:latest
    container_name: test-vue-deploy-app-cnt
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.docker.network: "${TRAEFIK_NETWORK:-web_network}"
      traefik.http.routers.test-vue-deploy-app.rule: "Host(`localhost`) && (Path(`/pyth0nhater/test-vue-deploy-app`) || PathPrefix(`/pyth0nhater/test-vue-deploy-app/`))"
      traefik.http.routers.test-vue-deploy-app.entrypoints: "web"
      traefik.http.services.test-vue-deploy-app.loadbalancer.server.port: "80"
      traefik.http.routers.test-vue-deploy-app.middlewares: "test-vue-deploy-app-strip"
      traefik.http.middlewares.test-vue-deploy-app-strip.stripprefix.prefixes: "/pyth0nhater/test-vue-deploy-app"
    networks:
      - web

networks:
  web:
    external: true
    name: "${TRAEFIK_NETWORK:-web_network}"
